### ISSUE TITLE
[BUG] All buttons are act like remove button

### ISSUE THREAD

**Issue by donggyu3728** [CAU-OSS-2019/team-project-team9#14]
**Describe the bug**
Scale and Rotate buttons are act like Remove button.

**To Reproduce**
1. Click scale or rotate button
2. The element disappears

**Expected behavior**
WBApexTool.ts => line 148
```c
    this.eventCollector.attachEvent(window, 'click', () => {
      this.remove();
    })
```
Maybe this line should be edited; this.remove *MUST* be called when remove button clicked only

**Chrome version**
 - 74

**Comment by jhaemin** [comment]
Thanks, I recognized the bug.
I'll fix it asap.

**Comment by jhaemin** [comment]
Since I resolved the bug perfectly, I close this issue.
