### ISSUE TITLE
[BUG] ApexTool buttons are not placed well if an inline element is selected

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team9#50]
**Describe the bug**
ApexTool buttons are not placed well if an inline element is selected. all buttons are placed at the same center place.

**To Reproduce**
1. Go to test url : https://github.com/CAU-OSS-2019/webuffet
2. Activate webuffet
3. Select an inline element like below.
![image](https://user-images.githubusercontent.com/38099251/58434836-9f0a2e00-80f8-11e9-8eff-f178492aa733.png)

**Expected behavior**
ApexTool buttons should be placed well.

**Screenshots**
![image](https://user-images.githubusercontent.com/38099251/58434855-bd702980-80f8-11e9-8137-d5f6a9214918.png)

**Chrome version**
 - 74

**Comment by jhaemin** [comment]
![Screen Shot 2019-05-28 at 11 22 10 AM](https://user-images.githubusercontent.com/19797697/58446234-e6b1a980-813a-11e9-9e83-68c88f8730db.png)

I fixed this problem in a new branch called 'fix-inline-element'.
After some additional polishing, we will merge it to the master branch.
Thanks for your issue report.

**Comment by jhaemin** [comment]
I'll leave this issue open until it's fully resolved and merged into the master branch.

**Comment by jhaemin** [comment]
#52
