### ISSUE TITLE
Extension file cannot be loaded

### ISSUE THREAD

**Issue by jowoni** [CAU-OSS-2019/team-project-team9#51]
Hello,

I have downloaded the project files and tried to load the chrome extension program as instructed in README but it seems there's some problem with the extension file.

![webuffet](https://user-images.githubusercontent.com/42177510/58747243-5f01cd00-84a3-11e9-8822-0288b6531a02.PNG)

Re-building the extension file may be the way to go.

Thank you

**Comment by jhaemin** [comment]
The error says it couldn't load the built file. So make sure you've followed the build instruction correctly.

1. Open terminal and go to the root directory. Root directory contains `package.json`.
2. Run the scripts below
```bash
$ npm install
$ npm run build
```
3. Check if the file `webuffet.built.js` is generated under the `/extension/build/` directory.
4. Load the directory 'extension' from the Chrome.

**Comment by jhaemin** [comment]
I close this issue since it's not directly related to the source codes.
