### ISSUE TITLE
[BUG] Some elements are not selected properly

### ISSUE THREAD

**Issue by jowoni** [CAU-OSS-2019/team-project-team9#55]
Hello

I tried the extension in the following link below.
https://everytime.kr/

However, when I select the element as the picture below, its parameter is not seen properly.
I am only able to fix the element in the original position and nothing else.

Hope this is useful for fixing the bug for some elements..
Thank you

![webuffet6](https://user-images.githubusercontent.com/42177510/58748067-890cbc80-84ae-11e9-8854-ab8c4b51673c.PNG)
![webuffet7](https://user-images.githubusercontent.com/42177510/58748068-8a3de980-84ae-11e9-8bc5-b728e3a54f85.PNG)

**Comment by jhaemin** [comment]
#50 duplicate
