### ISSUE TITLE
[BUG] ApexTool's size is wrong if you select an element, that inside another element whose size was changed by webuffet

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team9#56]
**Describe the bug**
ApexTool's size is wrong if you select an element, that inside another element whose size was changed by webuffet. It looks like follow the element's original size.

**To Reproduce**
1. Go to https://www.google.co.kr/

2. Select the element.
![image](https://user-images.githubusercontent.com/38099251/58749850-11e32280-84c6-11e9-9283-b6a2f11a8ae3.png)

3. Make the element's size bigger.
![image](https://user-images.githubusercontent.com/38099251/58749837-efe9a000-84c5-11e9-9117-3291cdf0796f.png)

4. Select the element again like below, that inside the previous element.
![image](https://user-images.githubusercontent.com/38099251/58749873-38a15900-84c6-11e9-914f-3c3143067260.png)

5. See error (like the screenshot)

**Expected behavior**
ApexTool's size should be bigger. Match with the element's new size.

**Screenshots**
![image](https://user-images.githubusercontent.com/38099251/58749783-338fda00-84c5-11e9-91a6-1ea29638588a.png)

**Chrome version**
 - 74

**Comment by jhaemin** [comment]
Hello again!

I fix this issue and leave a pull request. #57 

![Screen Shot 2019-06-01 at 11 58 51 PM](https://user-images.githubusercontent.com/19797697/58750189-20cbd400-84ca-11e9-89d8-e728074989e2.png)

Thank you for a priceless bug report.
