### ISSUE TITLE
[BUG] ApexTool isn't working well if parent element was rotated

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team9#58]
**Describe the bug**
I found the bug again. there is error if parent element was rotated. this issue is similar with #56.

**To Reproduce**
1. Go to https://www.google.co.kr
2. Rotate the element
![image](https://user-images.githubusercontent.com/38099251/58750690-95a20c80-84d0-11e9-9fd6-393589869544.png)

3. Select the child element
![image](https://user-images.githubusercontent.com/38099251/58750702-abafcd00-84d0-11e9-9b02-44d4df38bf12.png)

    - ApexTool is not rotated.
    - If you try to move the element, it doesn't move correctly.

**Expected behavior**
1. ApexTool's rotate degree should be correct.
2. Be able to move child elements correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/38099251/58750714-db5ed500-84d0-11e9-8946-915aede33276.png)

**Chrome version**
 - 74

**Comment by jhaemin** [comment]
Related to #56 #57 
Fix #60 

![Screen Shot 2019-06-02 at 2 15 27 AM](https://user-images.githubusercontent.com/19797697/58751946-46180c80-84e1-11e9-90ea-1d0b720770bf.png)

Thank you very much!
