### ISSUE TITLE
[BUG] I can't see naver mail even if I don't change anything with webuffet

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team9#59]
**Describe the bug**
I can't see naver mail even if I don't change anything, any elements with webuffet. This bug exists even after reinstallation. When I uninstall webuffet, this page looks well.

**To Reproduce**
1. Go to https://mail.naver.com/ and login
2. See error

**Expected behavior**
The page should look well.

**Screenshots**
![image](https://user-images.githubusercontent.com/38099251/58750893-93d94880-84d2-11e9-8e84-2224b1c0e834.png)

**Chrome version**
 - 74

**Comment by jhaemin** [comment]
Fix #60 

Thank you!
