### ISSUE TITLE
[BUG] not working in chrome

### ISSUE THREAD

**Issue by hoonv** [CAU-OSS-2019/team-project-team9#62]
**Describe the bug**

I built it( npm install & npm build), I installed it.
and i checked it installed 
To activate WEBuffet, press and hold anywhere inside the page for just 1 second. But there is no response.

**To Reproduce**

**Expected behavior**
it working

**Screenshots**

![image](https://user-images.githubusercontent.com/46335714/59327669-32607780-8d25-11e9-9fc0-e3c95305ec54.png)

![image](https://user-images.githubusercontent.com/46335714/59327809-a13dd080-8d25-11e9-9ed9-f9e6482f9752.png)

**Chrome version**
 - v74.0.3729.169 (64bit)

**Additional context**

**Comment by jhaemin** [comment]
We changed the way of activating it.
A menu will be shown in the context menu when you right-click on the page.
Thank you for your issue.
