### ISSUE TITLE
[BUG] webuffet activating in webuffet page

### ISSUE THREAD

**Issue by hoonv** [CAU-OSS-2019/team-project-team9#65]
**Describe the bug**
webuffet activating in webuffet page

**To Reproduce**
1 right click and activate webuffet
2 click plus button in webuffet page
3  and right click and activate webuffet, and  then activating in webuffet site 

**Expected behavior**
no activate in webuffet page

**Screenshots**
![image](https://user-images.githubusercontent.com/46335714/59855015-0b521780-93af-11e9-8bba-71fd0c793735.png)

**Chrome version**
 - [e.g. 67]

**Additional context**

**Comment by donggyu3728** [comment]
Hello. Thank you for your support about our project and reporting an issue.
I've been reviewed this problem - and I tried to fix this problem in branch `fix/issue#65`
In this fix, when 'activate webuffet' selected in context menu, the `main.ts` will send event to ApexTool and Selector to stop.
This fix will merged into branch `master` after tested by our project coworkers - You can try this version in branch `fix/issue#65`.
I'm very glad to find this problem and fix it. Thank you for your help.<br>
*This issue will be closed after related commit be merged into `master`*

**Comment by donggyu3728** [comment]
closed by commit `b7b48fe`
