### ISSUE TITLE
[BUG] It's moving when I didn't want it.

### ISSUE THREAD

**Issue by guioon** [CAU-OSS-2019/team-project-team9#67]
**Describe the bug**
It's moving when I didn't want it.

**To Reproduce**
In the github repository
I tried to move the text, but the button is moving with.

**Screenshots**
![딴것도 옮겨짐](https://user-images.githubusercontent.com/29909322/59900579-b0163880-9433-11e9-902e-c0e1a730a0f2.PNG)
![딴것도 옮겨짐2](https://user-images.githubusercontent.com/29909322/59900580-b2789280-9433-11e9-8e01-842ead5e7a99.PNG)

**Chrome version**
 -  75.0.3770.100

**Comment by jhaemin** [comment]
They are included in the same DOM element. It's a normal behaviour.
